# Generated by Django 3.0.4 on 2020-03-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_premium_user',
            field=models.BooleanField(default=True, verbose_name='premium'),
        ),
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.CharField(blank=True, max_length=30, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='profile',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=9, verbose_name='telephone'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_staff',
            field=models.BooleanField(default=True, verbose_name='staff'),
        ),
    ]
