# Generated by Django 3.0.4 on 2020-03-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_premium_user',
            field=models.BooleanField(default=False, verbose_name='premium'),
        ),
    ]
