# Generated by Django 3.0.4 on 2020-03-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propietario',
            name='isAdmin',
            field=models.BooleanField(default=False, verbose_name='Administrador'),
        ),
        migrations.AddField(
            model_name='propietario',
            name='isPresident',
            field=models.BooleanField(default=False, verbose_name='Presidente'),
        ),
    ]
