# Generated by Django 3.0.4 on 2020-04-01 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_auto_20200401_1712'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0008_auto_20200401_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propietario',
            name='apartment',
        ),
        migrations.AddField(
            model_name='propietario',
            name='apartment',
            field=models.ManyToManyField(null=True, to='community.Apartment'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
