# Generated by Django 3.0.4 on 2020-04-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_auto_20200401_1712'),
        ('profiles', '0009_auto_20200401_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='community',
            field=models.ManyToManyField(null=True, to='community.Community'),
        ),
    ]
