# Generated by Django 3.0.4 on 2020-04-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_auto_20200401_1712'),
        ('profiles', '0010_servicio_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='apartment',
            field=models.ManyToManyField(to='community.Apartment'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='community',
            field=models.ManyToManyField(to='community.Community'),
        ),
    ]
