# Generated by Django 3.0.4 on 2020-04-01 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_auto_20200401_1712'),
        ('profiles', '0011_auto_20200401_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquilino',
            name='apartment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leased', to='community.Apartment'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='apartment',
            field=models.ManyToManyField(related_name='owner', to='community.Apartment'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='community',
            field=models.ManyToManyField(related_name='community', to='community.Community'),
        ),
    ]
