# Generated by Django 3.0.4 on 2020-04-01 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20200401_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquilino',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='apartment',
        ),
    ]
