# Generated by Django 3.0.4 on 2020-04-02 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20200401_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='community',
        ),
    ]
