# Generated by Django 3.0.4 on 2020-04-01 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avenida', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('portal', models.CharField(blank=True, max_length=5)),
                ('codigoPostal', models.IntegerField()),
                ('poblacion', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('instalaciones', models.CharField(default='', max_length=50)),
                ('direcion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='community.Direction')),
            ],
        ),
    ]
