# Generated by Django 3.0.4 on 2020-04-01 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20200401_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piso', models.IntegerField()),
                ('puerta', models.CharField(max_length=5)),
                ('escalera', models.CharField(blank=True, max_length=25)),
                ('numTrastero', models.CharField(blank=True, max_length=25)),
                ('numCochera', models.CharField(blank=True, max_length=25)),
                ('comunity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='community.Community')),
            ],
        ),
    ]
