# Generated by Django 3.0.4 on 2020-04-01 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='comunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Community'),
        ),
    ]
