# Generated by Django 3.0.4 on 2020-04-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20200401_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='via',
            field=models.CharField(choices=[('Avda', 'Avenida'), ('C', 'Calle'), ('Plz', 'Plaza'), ('Pso', 'Paseo')], default='Avda', max_length=5),
            preserve_default=False,
        ),
    ]
