# Generated by Django 3.0.4 on 2020-04-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_direction_via'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='via',
            field=models.CharField(choices=[('Avda', 'Avenida'), ('C', 'Calle'), ('Plz', 'Plaza'), ('Ps', 'Paseo')], max_length=5),
        ),
    ]
