# Generated by Django 3.0.4 on 2020-04-01 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20200401_1746'),
        ('community', '0006_auto_20200401_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='profiles.Propietario'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='renter',
            field=models.ManyToManyField(null=True, related_name='renters', to='profiles.Inquilino'),
        ),
    ]
