# Generated by Django 3.0.4 on 2020-04-02 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_remove_servicio_community'),
        ('community', '0007_auto_20200401_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='services',
            field=models.ManyToManyField(related_name='employed', to='profiles.Servicio'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='profiles.Propietario'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='renter',
            field=models.ManyToManyField(related_name='renter', to='profiles.Inquilino'),
        ),
    ]
