# Generated by Django 3.0.4 on 2020-04-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_remove_servicio_community'),
        ('community', '0008_auto_20200402_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='instalaciones',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='services',
            field=models.ManyToManyField(default=[], related_name='employed', to='profiles.Servicio'),
        ),
    ]
