# Generated by Django 3.0.4 on 2020-04-02 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_remove_servicio_community'),
        ('community', '0009_auto_20200402_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='services',
        ),
        migrations.AddField(
            model_name='community',
            name='services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employed', to='profiles.Servicio'),
        ),
    ]
