# Generated by Django 3.0.4 on 2020-04-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_remove_servicio_community'),
        ('community', '0010_auto_20200402_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='services',
        ),
        migrations.AddField(
            model_name='community',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='employed', to='profiles.Servicio'),
        ),
    ]
