# Generated by Django 3.0.4 on 2020-04-09 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_auto_20200402_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='comunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='community.Community'),
        ),
        migrations.AlterField(
            model_name='community',
            name='instalaciones',
            field=models.CharField(blank=True, choices=[('Piscina', 'Piscina'), ('Parking', 'Parking'), ('Trasteros', 'Trasteros'), ('Jardin', 'Jardin'), ('Parque', 'Parque')], default='', max_length=50, null=True),
        ),
    ]
