# Generated by Django 3.0.4 on 2020-04-09 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0013_auto_20200409_0618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='comunity',
            new_name='community',
        ),
    ]
